name: Deploy Blogger App
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create .env file
        run: echo "BLOGGER_A=${{ secrets.BLOGGER_A }}" >> .env

      - name: Install dependencies  
        run: echo "Skipping npm install (no package.json found)"

      - name: Install gh-pages
        run: npm install gh-pages --save-dev

      - name: Deploy to GitHub Pages
        run: npm run deploy
